name: Fly Start/Stop Schedule

on:
  schedule:
    - cron: "0 1 * * *"   # Start 08:00 VN (UTC+7)
    - cron: "0 14 * * *"  # Stop 21:00 VN (UTC+7)
  workflow_dispatch:

jobs:
  start:
    if: github.event.schedule == '0 1 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl scale count 1 --app springeommmerceapp
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  stop:
    if: github.event.schedule == '0 14 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl scale count 0 --app springeommmerceapp
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
